branches:
  only:
    - master

matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r lib/py/requirements-dev.txt

      script:
        - cd lib/py
        - python -m pytest

      deploy:
        provider: script
        script: scripts/publish.sh
        on:
          branch: master

    - language: node_js
      node_js:
        - node

      before_install:
        - cd plugin

      script:
        - npm run lint

      deploy:
        provider: script
        script: npm run build && npm run semantic-release
        on:
          branch: master


    - language: node_js
      node_js:
        - node

      before_install:
        - cd lib/node

      deploy:
        provider: script
        script: npm run build && npm run semantic-release
        on:
          branch: master

