
branches:
  only:
    - master

matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r lib/py/requirements-dev.txt

      script:
        - cd lib/py
        - bash scripts/release.sh

