
branches:
  only:
    - master

matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r lib/py/requirements-dev.txt

      script:
        - cd lib/py
        - bash scripts/publish.sh

    - languange: node_js
      node_js: lts/*
      before_install:
        - cd plugin

      script:
        - npm run build && npm run semantic-release

