branches:
  only:
    - master

matrix:
  include:
    - language: python
      python: 3.6

      before_install:
          - cd lib/py

      install:
        - pip install -r requirements-dev.txt

      script:
        - python -m pytest

      deploy:
        provider: script
        skip_cleanup: true
        script: scripts/publish.sh
        on:
          branch: master

    - language: node_js
      node_js:
        - node

      before_install:
        - cd plugin

      script:
        - npm run lint

      deploy:
        provider: script
        skip_cleanup: true
        script: npm run build && npm run semantic-release
        on:
          branch: master


    - language: node_js
      node_js:
        - node

      before_install:
        - cd lib/node

      deploy:
        provider: script
        skip_cleanup: true
        script: npm run build && npm run semantic-release
        on:
          branch: master

